//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportID { get; set; }
        public int Owner { get; set; }
        public string Period { get; set; }
        public double AmountCharged { get; set; }
        public Nullable<double> AmountPaid { get; set; }
    
        public virtual Owners Owners { get; set; }
    }
}
